### ISSUE TITLE
Installation fails due to missing index.js

### ISSUE THREAD

**Issue by itsarjunsinh** [GetStream/stream-firebase-extensions#6]
The Authenticate with Stream chat extension installation fails during Cloud Function deployment stage.

> RESOURCE_ERROR at /deployments/firebase-ext-auth-chat/resources/createStreamUser: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":"Build failed: lib/index.js does not exist; Error ID: bc73f5cd"};

Same error for the other 3 functions.

### Steps to reproduce
1. Install via CLI or Firebase console (selected EU west 1 for CF location)
2. After keys, secrets have been saved, deploying Cloud Functions fails.

The following issue is similar:
FirebaseExtended/experimental-extensions#37

**Comment by jeevcat** [comment]
New versions of all extensions have now been published which should fix this issue.
